### ISSUE TITLE
Dynamic Command Handling & Hot-Reloading

### ISSUE THREAD

**Issue by clayjens** [TrueXPixels/sourcecode-public#14]
[Discordjs.guide](https://discordjs.guide) has a great section on [Dynamic Commands](https://discordjs.guide/command-handling/dynamic-commands.html), but it's quite basic. Having a command & hot-reload system similar to [Discord.js-commando](https://discordjs.guide/commando/first-command.html)'s would be great, considering that commando isn't know for being well optimized.

**Comment by lorencerri** [comment]
There will be an area on the site where you can request source code
