### ISSUE TITLE
Any Languages

### ISSUE THREAD

**Issue by Syn9673** [TrueXPixels/sourcecode-public#3]
On the previous site, you only allowed stuff for bots, and etc... Why not allow any languages? From the lowest to the highest. And also, maybe allow sharing of projects?

**Comment by lorencerri** [comment]
We'll be allowing all topics, submitters can either choose from the top 5 most popular ones or use the custom text field:
![Image](https://i.plexidev.org/f9sceXp)

The same will apply to languages:
![Image](https://i.plexidev.org/wlABCPk)

As for sharing projects, that may be something we'll look into. If you create another issue & describe it in more detail I can add it to the project board.
